# Generated by Django 4.2 on 2023-08-04 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0002_user_delete_note'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
